package com.example.awir.ws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-11-15T22:05:01.126+01:00
 * Generated source version: 3.5.4
 *
 */
@WebServiceClient(name = "PaymentService",
                  wsdlLocation = "classpath:wsdl/PaymentService.wsdl",
                  targetNamespace = "http://www.wi.zut.edu.pl/service/payment/v1.0")
public class PaymentService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wi.zut.edu.pl/service/payment/v1.0", "PaymentService");
    public final static QName PaymentServicePort = new QName("http://www.wi.zut.edu.pl/service/payment/v1.0", "PaymentServicePort");
    static {
        URL url = PaymentService_Service.class.getClassLoader().getResource("wsdl/PaymentService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PaymentService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/PaymentService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PaymentService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PaymentService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServicePort")
    public PaymentService getPaymentServicePort() {
        return super.getPort(PaymentServicePort, PaymentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServicePort")
    public PaymentService getPaymentServicePort(WebServiceFeature... features) {
        return super.getPort(PaymentServicePort, PaymentService.class, features);
    }

}
